### ISSUE TITLE
[bug]ADO 3.2 Plugin change the scanmode

### ISSUE THREAD

**Issue by joaquin386** [JoostVoskuil/azure-devops-gitleaks#106]
Hi,

There is a bug on the recently updted 3.2 plugin.
```
Task         : Gitleaks scan
Description  : Scan git repos (or files) for secrets using regex and entropy.
Version      : 3.2.0
Author       : Joost Voskuil (joost@foxhole.nl)
Help         : [More information](https://github.com/JoostVoskuil/azure-devops-gitleaks)
```

Before this was our line (see the `detect`):
```
/usr/local/bin/gitleaks detect XXXXXXXX
```

Now it is this (see `git`):
```
/usr/local/bin/gitleaks git XXXXXXXX
Error: unknown command "git" for "gitleaks"
Run 'gitleaks --help' for usage.
9:38AM FTL unknown command "git" for "gitleaks"
```

**Comment by JoostVoskuil** [comment]
@joaquin386 do you use the latest version of Gitleaks?

**Comment by joaquin386** [comment]
Yes I use the latest version
```
Starting: GitLeaks Scan
==============================================================================
Task         : Gitleaks scan
Description  : Scan git repos (or files) for secrets using regex and entropy.
Version      : 3.2.0
Author       : Joost Voskuil (joost@foxhole.nl)
Help         : [More information](https://github.com/JoostVoskuil/azure-devops-gitleaks)
==============================================================================
Thanks to Zachary Rice (https://github.com/zricethezav) for creating and maintaining gitleaks.
Thanks to Jesse Houwing (https://github.com/jessehouwing) for providing a gitleaks config that has most of Microsoft's deprecated credscan rules ported to it.
Thanks to Richard Gomez (https://github.com/rgmz) for keeping track of possible issues with the extension and config file updates.

/usr/local/bin/gitleaks git /azp/_work/1/s --config=/azp/_work/1/cicd-framework/modules/gates/gitleaks/v1/gitleaks.toml --redact --report-format=json --report-path=/azp/_work/_temp/gitleaks-report-4457af71-710d-5d71-a9bb-ac0e402178f6.json --exit-code=99
Error: unknown command "git" for "gitleaks"
Run 'gitleaks --help' for usage.
9:38AM FTL unknown command "git" for "gitleaks"
##[error]Execution errors occured. See log for details.
```

Here our task definition:
```
            - task: Gitleaks@3
              displayName: 'GitLeaks Scan'
              inputs:
                scanlocation: '$(Build.SourcesDirectory)'
                redact: true
                scanmode: 'all'
                configtype: 'custom'
                configfile: '$(Framework.FrameworkPath)/modules/gates/gitleaks/v1/gitleaks.toml'
                reportartifactname: gitleaks
                reportFormat: json
                taskfail: false
                ${{ if eq(coalesce(parameters.framework.module.inputs.gitleaksVersion, parameters.framework.service.gitleaksVersion, ''), '') }}:
                  customtoollocation: /usr/local/bin/
                version: latest
```
