### ISSUE TITLE
GitHub PR Validations are failing in ADO GitLeaks task. 

### ISSUE THREAD

**Issue by Raag007** [JoostVoskuil/azure-devops-gitleaks#30]
Hi - we are trying to integrate this tool.

Manual build triggers for detecting secrets work fine, but PR validation is failing with the below error. 

```
##[error]Cannot read property 'length' of null
```

Here is the code: 

```
          - task: Gitleaks@2
            inputs:
              scanlocation: '$(Build.SourcesDirectory)'
              configtype: 'predefined'
              predefinedconfigfile: 'GitleaksUdmCombo.toml'
              reportformat: 'sarif'
              verbose: true
            displayName: "Gitleaks Credential Scanner"
```

Happy to provide any other required information. 

Thank you in advance. Have a nice day!
