### ISSUE TITLE
Add multiple gitleaks tasks in Azure DevOps Pipeline

### ISSUE THREAD

**Issue by gotojeffray** [JoostVoskuil/azure-devops-gitleaks#54]
Hi there,
Could we add more than 1 gitleaks tasks in the pipeline?
```
  - job: GenerateArtifacts
    steps:
      - checkout: self  ### e.g  --->aks-microservice
      - checkout: terraform-modules

      - task: Gitleaks@2
        displayName: gitleaks-aks-microservice
        inputs:
          scanlocation: '$(Build.SourcesDirectory)/aks-microservice'
          configtype: 'custom'
          configfile: '$(Build.SourcesDirectory)/aks-microservice/.gitleaks.toml'
          reportformat: 'json'

      - task: Gitleaks@2
        displayName: gitleaks-terraform-modules
        inputs:
          scanlocation: '$(Build.SourcesDirectory)/terraform-modules'
          configtype: 'custom'
          configfile: '$(Build.SourcesDirectory)/aks-microservice/.gitleaks.toml'
          reportformat: 'json'
```

the 1st job works fine, but the 2nd job always gets the error:
```
1:04AM ERR [git] fatal: bad object 6ad170bc7c5a7e59145b5b1e6a17531666f1bcc2
```

the commit id 6ad170bc7c5a7e59145b5b1e6a17531666f1bcc2  belongs to the 1st(aks-microserice) not the 2nd repo(terrafrom-modules)

Thanks for any input.

**Comment by JoostVoskuil** [comment]
Hi @gotojeffray 

Can you change your pipeline in: 
```yaml
  steps:
      - checkout: self  ### e.g  --->aks-microservice
      - checkout: terraform-modules
         fetchDepth: 0
 ```
