### ISSUE TITLE
[git] fatal: bad object -- error="stdeer is not empty" 

### ISSUE THREAD

**Issue by ChrisHolman** [JoostVoskuil/azure-devops-gitleaks#86]
I've noticed weird behavior whilst using the GitLeaks ADO task. Please see below: 
 
**Describe the bug**
Using the GitLeaks Azure DevOps Task, which is part of a template being called inside Azure DevOps pipelines, it's often producing the following error:

```
9:24AM ERR [git] fatal: bad object 613989346268393a95e9218ab63e917629216914
9:24AM ERR  error="stderr is not empty"
9:24AM INF scan completed in 4.92ms
9:24AM INF no leaks found
```
The scan claims not to have found any leaks, but also produces an error which doesn't fail the step, even with `taskfail `defaulted to true. 

**To Reproduce**
1. Configure GitLeaks ADO task to run inside a template:

```
- task: Gitleaks@2
      inputs:
        scanlocation: ${{ parameters.gitleaks.scanlocation }}
        configtype: 'predefined'
        predefinedconfigfile: 'GitleaksUdmCombo.toml'
        scanmode: 'changes'
        reportformat: 'json'
        reportname: 'gitleaksreport'
        verbose: true
```
3. Call this template, from the service you wish to scan. ScanLocation parameter defaults to $(Build.SourcesDirectory), which in most scenarios is the correct location. 
4. Ensure there is more than one commit to scan, then observe the error. 

**Expected behavior**
Expect the scan to either produce a result and fail, or to not detect a leak, and pass. 

**Screenshots**
![image](https://github.com/user-attachments/assets/f234f11b-2c97-4f2c-89a2-2a4f52c376a2)

**Basic Info :**
 - OS: Ubuntu 22.04.04
 - Gitleaks Version:  2.9.0
