### ISSUE TITLE
Error: Cannot find module 'node:path' when using GitLeaks@2 task in Azure Devops build Pipeline

### ISSUE THREAD

**Issue by mohammedidris1** [JoostVoskuil/azure-devops-gitleaks#89]
Hi @JoostVoskuil , I am facing an issue when using GItLeaks@2 Task in my Azure Devops Build Pipeline. 
It was working fine all these days but started failing from yesterday. 
I am getting error when node; path is being imported. 

```

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:path'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/myagent/_work/_tasks/Gitleaks_11bd67d8-bfe7-497b-967d-e800eb673119/2.10.0/index.js:39:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)


```
# Gitleaks-scan.yml : 

```
parameters:
  - name: 'scanmode'
    displayName: 'type of scan'
    type: string
    default: 'prevalidation'

steps:
  # Run Gitleaks on Source Repository
  - task: Gitleaks@2
    inputs:
      configtype: 'custom'
      configfile: '$(Build.SourcesDirectory)/.gitleaks.toml'
      reportformat: 'sarif'
      scanmode: 'changes'
```

@JoostVoskuil could you please help me resolve this issue? 
Any help is appreciated. Thanks in advance.
